# Variables
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "New Room",
    "description": "This is a new room created via API."
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "What is the capital of France?",
    "answer": "Paris"
}

###

# Get room by ID
# @name getRoomById
GET {{baseUrl}}/rooms/{{roomId}}
Content-Type: application/json  

{
    "roomId": "5186ff26-2acf-4842-ba7b-97235e128451",
}